### ISSUE TITLE
Can't log in 

### ISSUE THREAD

**Issue by Sauron79** [ZencashOfficial/arizen#277] opened 2018-02-04 15:36 UTC
Guys,

I am worried. I was using Arizen 1.1.1 and despite trying to log in > 100 times I am unable to access my data. Now I upgraded to version 1.1.3 hoping the issue would be fixed but it's still there, and I can't log in. This is worrying. Please help me. I tried to shut down Arizen and reopen, and also restarted my computer several times.

Thanks,

Sauron79

**Comment by gsfakianakis** [comment] 2018-02-04 16:20
Please see #160 

Also answer the following questions and try the steps 1-3:

What i your OS ?
Did you do any restore or installed again your OS recently ?

Could you also try these ?

1. go to ~/.arizen/wallets and backup the username.awd file. Uninstall arizen, download again from github and verify the sha256 sum. If the sum is correct, install arizen and try to login again.

Download here: https://github.com/ZencashOfficial/arizen/releases
~/.arizen/wallets for windows is : %appdata%\Arizen\wallets
and for mac is: Users/username/Library/Application Support/Arizen

2. In your current pc make a new account and after you create it, try to login to the new account.
3. Having your wallet backed up. If possible go to another PC copy your username.awd file in the ~/.arizen/wallets, open arizen and try to login from there, using the same credentials.

**Comment by woky** [comment] 2018-02-04 19:24
duplicate of #160, see the last message there

**Closed by woky** 2018-02-04 19:24 UTC

**Comment by Sauron79** [comment] 2018-02-10 23:11
Hello. I tried to the steps in #160 and this has not helped. I am using a mac. I backed up the .AWD file and then I deleted the version of Arizen I was using. I then downloaded the latest version of Arizen. I can open a new wallet fine, but the older wallet (the subject of this message) is no longer opening. I am worried I have lost my ZEN. Please help me.

**Comment by woky** [comment] 2018-02-10 23:57
@Sauron79 I was referring to this: https://github.com/ZencashOfficial/arizen/issues/160#issuecomment-362867374 Ignore other suggestions and try this.
